### TODOS LOS USUARIOS ###
GET http://localhost:3000/api/v1/users



### CREAR NUEVO USUARIO ###
POST http://localhost:3000/api/v1/users/create
Content-Type:  application/json

{
  "name": "leonardo",
  "lastName": "Brem",
  "password": 123,
  "password2": 123,
  "email": "busszzxx@uci.cu"
}




### LOGIN ###
POST http://localhost:3000/api/v1/auth/login
Accept-Language: Es
Content-Type:  application/json

{

  "password": "123",

  "email": "buzz@uci.cu"
}


### Translation Test
POST http://localhost:3000/api/v1/auth/me
Accept-Language: Es
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OGI1NjhmOTJmYjIzNDY5YWVhMDI4YiIsIm5hbWUiOiJmaXp6IiwibGFzdE5hbWUiOiJCcmVtIiwiZW1haWwiOiJidXp6QHVjaS5jdSIsImlhdCI6MTcwNDM0MzY4NiwiZXhwIjoxNzA2OTM1Njg2fQ.BJWxYf7vcOigxN2P2EGXxPnQn1_VNZsKFhFvZcbtk7o