### TODOS LOS USUARIOS ###
GET http://localhost:3000/api/v1/users



### CREAR NUEVO USUARIO ###
POST http://localhost:3000/api/v1/users/create
Content-Type:  application/json

{
  "name": "leonardo",
  "lastName": "Brem",
  "password": 123,
  "password2": 123,
  "email": "busszzxx@uci.cu"
}




### LOGIN ###
POST http://localhost:3000/api/v1/auth/login
Accept-Language: Es
Content-Type:  application/json

{

  "password": "123",

  "email": "javi@uci.cu"
}


### Translation Test
POST http://localhost:3000/api/v1/auth/me
Accept-Language: Es
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OTcwODI3ZTVlYjI4ZGRhNzAzNzc4ZSIsIm5hbWUiOiJKYXZpZXIiLCJsYXN0TmFtZSI6IkFudG9uaW8gUm9xdWUiLCJlbWFpbCI6ImphdmlAdWNpLmN1IiwiaWF0IjoxNzA0Mzk2ODU4LCJleHAiOjE3MDY5ODg4NTh9.PSKgPqspQzFjPT1pHSo235VHpGlCfWz8HknmIEHVRyY